# Generated by Django 4.0.4 on 2023-11-16 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filePath', models.FileField(upload_to='uploads/')),
                ('dateUploaded', models.DateTimeField(auto_now_add=True)),
                ('numberOfProductor', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSurface', models.CharField(max_length=100)),
                ('surfaceParcelle', models.FloatField()),
                ('localisation', models.BooleanField(default=False)),
                ('polygone', models.BooleanField(default=False)),
                ('variete', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('typeQuestion', models.IntegerField()),
                ('formulaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.formulaire')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponseBio', models.CharField(max_length=100, null=True)),
                ('libelle', models.CharField(max_length=100, null=True)),
                ('fichier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.file')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('nomPrenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('contact', models.IntegerField(null=True)),
                ('village', models.CharField(max_length=100, null=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.parcelle')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.producteur'),
        ),
        migrations.AddField(
            model_name='cooperative',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.zone'),
        ),
    ]
