# Generated by Django 4.0.4 on 2023-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='numberOfProductor',
            field=models.IntegerField(default=0),
        ),
    ]
