# Generated by Django 4.2.3 on 2023-07-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formulaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codeSurface', models.CharField(max_length=100)),
                ('surfaceParcelle', models.FloatField()),
                ('localisation', models.BooleanField(default=False)),
                ('polygone', models.BooleanField(default=False)),
                ('variete', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('typeQuestion', models.IntegerField()),
                ('poidsBio', models.IntegerField()),
                ('formulaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.formulaire')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponseBio', models.CharField(max_length=100)),
                ('libelle', models.CharField(max_length=100)),
                ('fichier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.file')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.question')),
            ],
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('nomPrenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, null=True)),
                ('contact', models.IntegerField()),
                ('village', models.CharField(max_length=100)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.cooperative')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelleQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcelle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.parcelle')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.question')),
            ],
        ),
        migrations.AddField(
            model_name='cooperative',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.zone'),
        ),
    ]
