# Generated by Django 4.2.3 on 2023-08-06 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0002_cooperative_formulaire_parcelle_question_zone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelle',
            name='producteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='agriApp.producteur'),
        ),
    ]
