# Generated by Django 4.2.3 on 2023-08-07 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0003_parcelle_producteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='poidsBio',
        ),
    ]
