# Generated by Django 4.2.3 on 2023-08-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0004_remove_question_poidsbio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producteur',
            name='contact',
            field=models.IntegerField(null=True),
        ),
    ]
