# Generated by Django 4.2.3 on 2023-08-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agriApp', '0005_alter_producteur_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='libelle',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reponse',
            name='reponseBio',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
